### ISSUE TITLE
data require

### ISSUE THREAD

**Issue by WatsonWangZh** [kracr/document-level-relation-extraction#3]
Thanks for your early reply. But there is still an issue:

1.Traceback (most recent call last): File "train.py", line 252, in train(opt) File "train.py", line 149, in train output = model(words=d['context_idxs'], File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl result = self.forward(*input, **kwargs) File "/hy-tmp/document-level-relation-extraction/DocRE-CLiP/code/models/DRN.py", line 401, in forward if(params["modeltype"]=="test"): KeyError: 'modeltype'

Could you provide the /DOCREDlink/linkpredictiondata dataset? How to split the dataset?

**Comment by joker1125** [comment]
Hello, I encountered an issue while reviewing your experiment. I need the linkpredictiondata, but I couldn't find the code that generates this file.

**Comment by nanyu999** [comment]
+1

**Comment by vinhpad** [comment]
+2 :'(

**Comment by w15083012839** [comment]
有人可以复现完全吗
